### ISSUE TITLE
Hour Strike App not working :(

### ISSUE THREAD

**Issue by zloid** [Weiming-Hu/hourstrike#1]
Hi! Thanks for the app, but for some reason it doesn't work for me on Bangle.js.
Any idea why? Could there be conflicts with other apps?

**Comment by Weiming-Hu** [comment]
Strange. Let me take a look perhaps during the weekend! Thanks for reporting.

**Comment by Weiming-Hu** [comment]
Looks like it is indeed an app conflict issue. The app stopped working for me from time to time. I have a bunch of apps (boo loaders, clocks, and more) installed. When I reset the watch and installed some apps back, it seems to work just fine.

Could you let me know a list of your apps? Maybe I can try to re-create the situation that led to its malfunctioning. Or at least, pin point the app that breaks it.

**Comment by zloid** [comment]
The app is now working!

What I did: I updated the firmware to 2v11 and applications requiring an update (including Bootloader). But it started working specifically after updating the applications on Bangle.js

Thanks again for the useful app :)
